<a href="https://colab.research.google.com/github/KrzysztofNa/data_science_bootcamp/blob/master/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

www.numpy.org - dokumentacja i strona o numpy

In [2]:
import numpy as np
np.__version__

'1.18.5'

In [5]:
# sprawdzanie atrybutów numpy
#print(dir(np))

In [7]:
#help(np.array)

In [8]:
# podstawowy obiekt w numpy - tablica (musi składać się z takich samych elementów)
x=np.array([1, 3])
x

array([1, 3])

In [9]:
print(x)

[1 3]


In [11]:
# klasa ndarray (wymiar)
x.ndim

1

In [12]:
# kształt
x.shape

(2,)

In [13]:
#rozmiar (ilość elementów)
x.size

2

In [14]:
# typ danych
x.dtype

dtype('int64')

In [16]:
x = np.array([1.2, 3.3, 4.1])
x

array([1.2, 3.3, 4.1])

In [19]:
# tablice dwuwymiarowe
x = np.array([[1, 2], [-3, 1]])

In [20]:
x.ndim

2

In [23]:
x.shape

(2, 2)

In [25]:
x=np.array([[1,2,3], [4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [26]:
x.shape

(2, 3)

In [29]:
# tablice trójwymiarowe
x=np.array([[[4,5,6], [3,2,1]], 
            [[5,4,6], [4,2,1]]])
print(x)

[[[4 5 6]
  [3 2 1]]

 [[5 4 6]
  [4 2 1]]]


In [30]:
x.ndim

3

In [31]:
x.shape

(2, 2, 3)