<a href="https://colab.research.google.com/github/KrzysztofNa/data_science_bootcamp/blob/master/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

www.numpy.org - dokumentacja i strona o numpy

In [3]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
# sprawdzanie atrybutów numpy
#print(dir(np))

In [ ]:
#help(np.array)

In [ ]:
# podstawowy obiekt w numpy - tablica (musi składać się z takich samych elementów)
x=np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
# klasa ndarray (wymiar)
x.ndim

1

In [ ]:
# kształt
x.shape

(2,)

In [ ]:
#rozmiar (ilość elementów)
x.size

2

In [ ]:
# typ danych
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.2, 3.3, 4.1])
x

array([1.2, 3.3, 4.1])

In [ ]:
# tablice dwuwymiarowe
x = np.array([[1, 2], [-3, 1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x=np.array([[1,2,3], [4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
x.shape

(2, 3)

In [ ]:
# tablice trójwymiarowe
x=np.array([[[4,5,6], [3,2,1]], 
            [[5,4,6], [4,2,1]]])
print(x)

[[[4 5 6]
  [3 2 1]]

 [[5 4 6]
  [4 2 1]]]


In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

In [5]:
# ustalanie typów danych
A = np.array([1.0, 2, 4], dtype='complex')
A.dtype

dtype('complex128')

In [6]:
A

array([1.+0.j, 2.+0.j, 4.+0.j])

In [7]:
A=np.array([True, False])
A.dtype

dtype('bool')

In [9]:
#mozna optymalizowac zmniejszajac zuzycie pamieci
A=np.array([24, 12, 4], dtype=np.int8)
A.dtype

dtype('int8')

In [10]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [15]:
np.arange(start=2, stop=10, step=0.25)

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25, 6.5 , 6.75, 7.  , 7.25,
       7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  , 9.25, 9.5 , 9.75])

In [16]:
np.linspace(start=1, stop=2, num=10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [19]:
A=np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])