<a href="https://colab.research.google.com/github/KrzysztofNa/data_science_bootcamp/blob/master/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.3.0'

In [12]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

In [13]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

In [14]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.add(Dense(units=2))

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 44        
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 10        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


In [16]:
from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [17]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [18]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [19]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [20]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [21]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])

In [22]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [23]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [24]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 9         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


In [25]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

In [26]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

In [27]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [28]:
data[:3]

array([[ 0.39312098, -0.20514646, -0.12306439,  0.79010663,  0.94975144,
         0.46475462, -3.01537895, -0.67314074,  0.34587551, -0.71679111,
        -1.25731873,  0.75623871,  0.61925238,  0.31168922, -1.1562804 ,
        -1.27597227, -1.22918515, -0.03511435, -0.23292722,  0.11293023,
         2.05135103, -0.43442799, -0.80954455,  1.11258744,  1.18297619,
         1.92952437,  0.14163553, -1.68849279, -1.07207748, -0.35013082,
         0.29778052, -0.41408193, -0.31021119,  0.01147126, -1.12855276,
        -1.37750956,  0.34059064,  0.45119368,  1.06132787, -0.7612636 ,
         0.75320049,  0.73102091,  0.41795915, -1.06679347, -0.9962961 ,
        -0.85660928,  0.65724357, -1.19324354,  0.7818827 ,  0.32369531,
         0.46458845, -0.26289961, -0.20431247,  1.06802393, -0.22487513,
         1.53325727,  0.97761071, -0.67416554,  1.32358668, -0.64196628,
        -0.56470144,  0.32275395, -1.30963006, -1.28124665,  0.672992  ,
         0.43885102, -0.95837764,  1.02900545,  1.0

In [29]:
labels[:10]

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0]])

In [30]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 1s 2ms/step - loss: 0.7536 - accuracy: 0.5012
Epoch 2/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6967 - accuracy: 0.5412
Epoch 3/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6760 - accuracy: 0.5764
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6613 - accuracy: 0.5978
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6476 - accuracy: 0.6213
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6332 - accuracy: 0.6473
Epoch 7/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6201 - accuracy: 0.6655
Epoch 8/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6062 - accuracy: 0.6764
Epoch 9/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5928 - accuracy: 0.6933
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5797 - accuracy: 0.7008

In [31]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20
157/157 [==============================] - 0s 1ms/step - loss: 0.7607 - accuracy: 0.4990
Epoch 2/20
157/157 [==============================] - 0s 1ms/step - loss: 0.7054 - accuracy: 0.5318
Epoch 3/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6858 - accuracy: 0.5587
Epoch 4/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6724 - accuracy: 0.5805
Epoch 5/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6613 - accuracy: 0.6015
Epoch 6/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6506 - accuracy: 0.6211
Epoch 7/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6404 - accuracy: 0.6366
Epoch 8/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6306 - accuracy: 0.6508
Epoch 9/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6205 - accuracy: 0.6684
Epoch 10/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6111 - accuracy: 0.6729

In [32]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
250/250 [==============================] - 0s 2ms/step - loss: 0.7647 - accuracy: 0.5026 - val_loss: 0.7282 - val_accuracy: 0.4950
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6947 - accuracy: 0.5514 - val_loss: 0.7237 - val_accuracy: 0.4895
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6747 - accuracy: 0.5795 - val_loss: 0.7254 - val_accuracy: 0.4855
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6601 - accuracy: 0.6087 - val_loss: 0.7273 - val_accuracy: 0.4840
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6464 - accuracy: 0.6305 - val_loss: 0.7303 - val_accuracy: 0.4810
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6316 - accuracy: 0.6556 - val_loss: 0.7382 - val_accuracy: 0.4760
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6176 - accuracy: 0.6691 - val_loss: 0.7457 - val_accuracy: 0.4830
Epoch 

In [33]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [34]:
history

In [35]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [36]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
250/250 [==============================] - 0s 2ms/step - loss: 0.7510 - accuracy: 0.5107 - val_loss: 0.7327 - val_accuracy: 0.4920
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6932 - accuracy: 0.5471 - val_loss: 0.7265 - val_accuracy: 0.4980
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6716 - accuracy: 0.5841 - val_loss: 0.7288 - val_accuracy: 0.4995
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6554 - accuracy: 0.6102 - val_loss: 0.7307 - val_accuracy: 0.5050
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6399 - accuracy: 0.6374 - val_loss: 0.7363 - val_accuracy: 0.5045
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6245 - accuracy: 0.6580 - val_loss: 0.7402 - val_accuracy: 0.5055
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6083 - accuracy: 0.6810 - val_loss: 0.7469 - val_accuracy: 0.5025
Epoch 

In [37]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5,1))

In [38]:
model.predict(test_data)

array([[0.52625287],
       [0.5250127 ],
       [0.12772885],
       [0.3055517 ],
       [0.7441598 ]], dtype=float32)

In [39]:
model.predict_proba(test_data)

Instructions for updating:
Please use `model.predict()` instead.


array([[0.52625287],
       [0.5250127 ],
       [0.12772885],
       [0.3055517 ],
       [0.7441598 ]], dtype=float32)

In [40]:
model.predict_classes(test_data)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[1],
       [1],
       [0],
       [0],
       [1]], dtype=int32)

In [47]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [48]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 0s 1ms/step - loss: 0.7436 - accuracy: 0.4943
Epoch 2/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6935 - accuracy: 0.5421
Epoch 3/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6757 - accuracy: 0.5750
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6620 - accuracy: 0.6012
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6484 - accuracy: 0.6261
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6347 - accuracy: 0.6449
Epoch 7/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6195 - accuracy: 0.6692
Epoch 8/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6055 - accuracy: 0.6772
Epoch 9/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5913 - accuracy: 0.6929
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5775 - accuracy: 0.7044

In [43]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [44]:
labels[1]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [46]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20


ValueError: ignored

In [49]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [50]:
labels[:10]

array([49.9562161 , 11.31078059, 23.04366016, 19.67338941, 37.31308563,
       29.76904106, 24.44430977, 37.9833456 ,  4.67821421,  9.64271809])

In [51]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 0s 1ms/step - loss: 248.7872 - val_loss: 213.4882
Epoch 2/30
250/250 [==============================] - 0s 1ms/step - loss: 211.8299 - val_loss: 214.1707
Epoch 3/30
250/250 [==============================] - 0s 1ms/step - loss: 211.3808 - val_loss: 213.2477
Epoch 4/30
250/250 [==============================] - 0s 1ms/step - loss: 210.9645 - val_loss: 213.7995
Epoch 5/30
250/250 [==============================] - 0s 1ms/step - loss: 210.6771 - val_loss: 213.7362
Epoch 6/30
250/250 [==============================] - 0s 1ms/step - loss: 210.1131 - val_loss: 214.3911
Epoch 7/30
250/250 [==============================] - 0s 1ms/step - loss: 209.9465 - val_loss: 215.5995
Epoch 8/30
250/250 [==============================] - 0s 1ms/step - loss: 209.4624 - val_loss: 214.0512
Epoch 9/30
250/250 [==============================] - 0s 1ms/step - loss: 209.4504 - val_loss: 214.5215
Epoch 10/30
250/250 [==============================] - 0s 1ms/st

In [52]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
250/250 [==============================] - 0s 2ms/step - loss: 13.9150 - mse: 278.7943 - val_loss: 12.6888 - val_mse: 215.2067
Epoch 2/10
250/250 [==============================] - 0s 1ms/step - loss: 12.6154 - mse: 212.5299 - val_loss: 12.6335 - val_mse: 212.6458
Epoch 3/10
250/250 [==============================] - 0s 1ms/step - loss: 12.5918 - mse: 212.0315 - val_loss: 12.6882 - val_mse: 215.1656
Epoch 4/10
250/250 [==============================] - 0s 1ms/step - loss: 12.5812 - mse: 211.8499 - val_loss: 12.6485 - val_mse: 213.3353
Epoch 5/10
250/250 [==============================] - 0s 1ms/step - loss: 12.5713 - mse: 211.3341 - val_loss: 12.6474 - val_mse: 213.2681
Epoch 6/10
250/250 [==============================] - 0s 1ms/step - loss: 12.5581 - mse: 211.1633 - val_loss: 12.6317 - val_mse: 212.7144
Epoch 7/10
250/250 [==============================] - 0s 1ms/step - loss: 12.5472 - mse: 210.6118 - val_loss: 12.6276 - val_mse: 212.6335
Epoch 8/10
250/250 [==============

In [53]:
test_data = np.random.random((10, 150))
model.predict(test_data)

array([[24.464796],
       [22.11797 ],
       [22.364096],
       [24.133417],
       [24.13384 ],
       [23.036585],
       [25.306643],
       [19.34906 ],
       [21.357706],
       [23.223774]], dtype=float32)